
import json

def update_chapter_2():
    file_path = r'c:\Users\eleven\triet-utt\exam\chuong_2.json'
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    explanations = {
        1: "Chủ nghĩa duy vật thời cổ đại thường đồng nhất vật chất với một hay một số dạng cụ thể hữu hình như nước (Thales), lửa (Heraclit), không khí (Anaximens).",
        2: "Đêmôcrit (Democritus) là nhà triết học Hy Lạp cổ đại nổi tiếng với quan niệm vật chất là nguyên tử - những hạt nhỏ bé không thể phân chia.",
        3: "Thales (Ta-lét) là nhà triết học đầu tiên của Hy Lạp cổ đại, ông quan niệm bản nguyên của thế giới là Nước.",
        4: "Heraclit (Hê-ra-clít) cho rằng Lửa là bản nguyên của thế giới, ngọn lửa vĩnh cửu không ngừng bùng cháy và tàn lụi.",
        5: "Chủ nghĩa duy vật thế kỷ XVII-XVIII (siêu hình) chịu ảnh hưởng mạnh của cơ học cổ điển Newton, nên thường quy mọi hình thức vận động về vận động cơ học.",
        6: "Chủ nghĩa duy vật biện chứng khẳng định vận động là phương thức tồn tại của vật chất, là tuyệt đối và vĩnh viễn; còn đứng im chỉ là tương đối, tạm thời trong một quan hệ nhất định.",
        7: "Chủ nghĩa duy tâm (nhất là duy tâm chủ quan) cho rằng ý thức/tinh thần có trước và quyết định vật chất, sinh ra thế giới.",
        8: "Định nghĩa kinh điển về vật chất của V.I.Lênin được trình bày trong tác phẩm 'Chủ nghĩa duy vật và chủ nghĩa kinh nghiệm phê phán' (1909).",
        9: "Theo CNDV biện chứng, ý thức là hình ảnh chủ quan của thế giới khách quan. Nó là sự phản ánh thế giới vật chất vào bộ óc con người.",
        10: "Phản ánh ý thức là hình thức phản ánh cao nhất, chỉ có ở con người, mang tính năng động, sáng tạo.",
        11: "Động vật bậc cao có hệ thần kinh phát triển có thể đạt đến hình thức phản ánh tâm lý (tâm lý động vật), chưa phải là ý thức.",
        12: "Phản ánh năng động, sáng tạo là đặc trưng cơ bản của ý thức, chỉ được thực hiện ở bộ óc người - dạng vật chất có tổ chức cao nhất.",
        13: "Nguồn gốc tự nhiên của ý thức bao gồm hai yếu tố: Bộ óc con người (cơ quan vật chất) và Sự tác động của thế giới bên ngoài lên bộ óc (nguồn thông tin).",
        14: "Nguồn gốc xã hội của ý thức, yếu tố quyết định trực tiếp sự ra đời của ý thức, bao gồm Lao động và Ngôn ngữ.",
        15: "Bản chất của ý thức là sự phản ánh tích cực, tự giác, năng động, sáng tạo thế giới khách quan vào bộ óc người; là hình ảnh chủ quan của thế giới khách quan.",
        16: "Ý thức là 'hình ảnh chủ quan' vì nó bị khúc xạ qua lăng kính chủ quan (trình độ, kinh nghiệm, cảm xúc) của mỗi người, nhưng nội dung phản ánh là khách quan.",
        17: "Trong kết cấu của ý thức (theo chiều ngang), Tri thức là yếu tố cơ bản và cốt lõi nhất. Không có tri thức thì không có ý thức.",
        18: "Ph.Ăngghen chia vận động thành 5 hình thức cơ bản: Cơ học, Vật lý, Hóa học, Sinh học, và Xã hội.",
        19: "Vận động Cơ học (sự di chuyển vị trí trong không gian) là hình thức vận động thấp nhất, đơn giản nhất.",
        20: "Vận động Xã hội là hình thức vận động cao nhất, phức tạp nhất, bao hàm các hình thức vận động thấp hơn.",
        21: "CNDV biện chứng khẳng định vật chất quyết định ý thức (về nguồn gốc, nội dung, bản chất...), nhưng ý thức có tính độc lập tương đối và tác động trở lại vật chất thông qua hoạt động thực tiễn.",
        22: "Chủ nghĩa duy vật siêu hình thường tuyệt đối hóa vai trò của vật chất, phủ nhận hoặc không thấy được tính độc lập tương đối và sự tác động trở lại của ý thức.",
        23: "Ý thức không trực tiếp thay đổi được thực tại, nó phải thông qua 'hoạt động thực tiễn' của con người mới tác động trở lại vật chất.",
        24: "Quan điểm lịch sử - cụ thể yêu cầu xem xét sự vật trong không gian, thời gian cụ thể và những điều kiện, hoàn cảnh lịch sử cụ thể sinh ra nó.",
        25: "Cần tránh các quan điểm sai lầm như: Phiến diện (chỉ thấy một mặt), Chiết trung (lắp ghép vô nguyên tắc), Ngụy biện (đánh tráo khái niệm, cái phụ thành cái chính).",
        26: "Ngụy biện là lối tư duy đánh tráo vị trí, vai trò của các mối liên hệ, coi cái cơ bản thành không cơ bản hoặc ngược lại nhằm đạt mục đích chủ quan.",
        27: "Phát triển là khuynh hướng chung của thế giới, mang tính Khách quan (không phụ thuộc ý muốn), Phổ biến (mọi lĩnh vực), Đa dạng và phong phú.",
        28: "Phát triển là quá trình vận động theo khuynh hướng đi lên: từ thấp đến cao, từ đơn giản đến phức tạp, từ kém hoàn thiện đến hoàn thiện hơn.",
        29: "Quan điểm phát triển đối lập với quan điểm bảo thủ, trì trệ, định kiến. Nên phương án D (bảo thủ, định kiến) là không phải quan điểm của CNDV biện chứng.",
        30: "Quan điểm phát triển yêu cầu không chỉ nắm bắt cái hiện tại mà còn phải thấy được khuynh hướng phát triển trong tương lai của sự vật.",
        31: "Cái chung là phạm trù chỉ những mặt, những thuộc tính không những có ở một sự vật mà còn lặp lại trong nhiều sự vật, hiện tượng khác.",
        32: "Mối liên hệ nhân quả mang tính Khách quan (tồn tại ngoài ý muốn), Phổ biến (mọi sự vật đều có nguyên nhân), và Tất yếu (nguyên nhân nhất định sinh ra kết quả).",
        33: "Chất là tính quy định khách quan vốn có của sự vật, là sự thống nhất hữu cơ của các thuộc tính làm cho sự vật là nó chứ không phải cái khác.",
        34: "Độ là khoảng giới hạn mà trong đó sự thay đổi về lượng chưa dẫn đến sự thay đổi căn bản về chất của sự vật.",
        35: "Bước nhảy là giai đoạn chuyển hóa về chất của sự vật do những thay đổi về lượng trước đó gây ra (khi vượt quá độ).",
        36: "Phủ định biện chứng là sự thay thế cái cũ bằng cái mới, nhưng có tính kế thừa những yếu tố tích cực của cái cũ (phủ định của phủ định).",
        37: "Quy luật chuyển hóa từ những sự thay đổi về lượng thành những sự thay đổi về chất và ngược lại chỉ ra cách thức của sự vận động và phát triển.",
        38: "Quy luật thống nhất và đấu tranh của các mặt đối lập (Quy luật mâu thuẫn) vạch ra nguồn gốc và động lực của sự vận động và phát triển.",
        39: "Quy luật phủ định của phủ định vạch ra khuynh hướng của sự phát triển: tiến lên nhưng theo đường xoáy ốc (quanh co, phức tạp).",
        40: "Thực tiễn là toàn bộ hoạt động vật chất có mục đích, mang tính lịch sử - xã hội của con người nhằm cải tạo tự nhiên và xã hội.",
        41: "Nhận thức cảm tính (Trực quan sinh động) là giai đoạn đầu tiên, thấp nhất của quá trình nhận thức, phản ánh trực tiếp vẻ ngoài của sự vật.",
        42: "Nhận thức cảm tính đem lại những hiểu biết về đặc điểm bên ngoài, cụ thể, cảm tính của sự vật, chưa đi sâu vào bản chất.",
        43: "Nhận thức lý tính (Tư duy trừu tượng) phản ánh gián tiếp, trừu tượng và khái quát, đi sâu vào bản chất, quy luật của sự vật.",
        44: "Chân lý là những tri thức phù hợp với hiện thực khách quan và đã được thực tiễn kiểm nghiệm, chứng minh là đúng đắn.",
        45: "Con đường biện chứng của nhận thức: 'Từ trực quan sinh động đến tư duy trừu tượng, và từ tư duy trừu tượng đến thực tiễn' (Lênin).",
        46: "Đặc điểm chung của CNDV cổ đại là đồng nhất vật chất với vật thể cụ thể (dạng hữu hình, cảm tính).",
        47: "Chủ nghĩa duy vật trước Mác (bao gồm CNDV siêu hình) hiểu vật chất là những vật thể cụ thể, chứ chưa hiểu vật chất là một phạm trù triết học khái quát.",
        48: "Cuộc khủng hoảng vật lý học cuối XIX đầu XX chứng minh rằng quan niệm đồng nhất vật chất với khối lượng/nguyên tử là sai lầm, chứ không phải vật chất bị tiêu tan. Nó cho thấy giới hạn nhận thức cũ bị phá vỡ.",
        49: "Triết học Mác-Lênin không đồng nhất vật chất với vật thể cụ thể, mà coi vật chất là thực tại khách quan tồn tại độc lập với ý thức.",
        50: "Vật chất với tư cách là phạm trù triết học (thế giới vật chất) là vô hạn, vô tận, vĩnh viễn; còn các dạng vật chất cụ thể thì có sinh có diệt.",
        51: "Thuộc tính cơ bản nhất của vật chất để phân biệt với ý thức là 'Thực tại khách quan' (tồn tại bên ngoài và độc lập với ý thức).",
        52: "Theo định nghĩa của Lênin, vật chất tồn tại khách quan (bên ngoài ý thức) và con người có khả năng nhận thức được nó (chép lại, chụp lại).",
        53: "Ph.Ăngghen khẳng định: 'Vận động là phương thức tồn tại của vật chất, là thuộc tính cố hữu của vật chất'. Không có vật chất không vận động.",
        54: "Không gian và thời gian là những hình thức tồn tại của vật chất đang vận động. Không có không gian, thời gian thuần túy tách rời vật chất.",
        55: "Quan điểm CNDV biện chứng: Không gian và thời gian gắn liền với nhau và gắn liền với vật chất vận động.",
        56: "Thế giới vật chất là một chỉnh thể thống nhất. Quan điểm cho rằng thế giới bao gồm những bộ phận riêng biệt, tách rời là quan điểm siêu hình.",
        57: "Chủ nghĩa duy tâm khách quan (như Platon, Hegel) coi 'Ý niệm tuyệt đối' hay tinh thần vũ trụ là bản thể sinh ra thế giới.",
        58: "Chủ nghĩa duy tâm chủ quan (như Berkeley) coi sự vật là 'phức hợp các cảm giác', tuyệt đối hóa vai trò của cảm giác/ý thức cá nhân.",
        59: "Lao động là yếu tố quyết định trực tiếp biến vượn thành người, tách con người khỏi thế giới động vật.",
        60: "Ngôn ngữ là hệ thống tín hiệu vật chất (vỏ vật chất của tư duy) cần thiết để khái quát hóa và giao tiếp, trao đổi thông tin.",
        61: "Lao động (hoạt động thực tiễn) là nguồn gốc trực tiếp và quan trọng nhất quyết định sự ra đời và phát triển của ý thức.",
        62: "Sự khác nhau cơ bản là phản ánh ý thức mang tính 'năng động, sáng tạo', còn các hình thức phản ánh khác (vật lý, sinh học) mang tính thụ động hoặc bản năng.",
        63: "Ý thức tác động đến vật chất thông qua hoạt động thực tiễn của con người (chỉ đạo, hướng dẫn hành động).",
        64: "CNDV biện chứng khẳng định vật chất quyết định nội dung, nguồn gốc, bản chất của ý thức; ý thức là sự phản ánh vật chất.",
        65: "CNDV siêu hình thường tuyệt đối hóa vai trò của vật chất, coi ý thức chỉ là sự phản ánh thụ động, máy móc, phủ nhận tính độc lập tương đối.",
        66: "Mối liên hệ phổ biến là sự tác động qua lại, chuyển hóa lẫn nhau giữa các sự vật, hiện tượng và giữa các mặt bên trong sự vật.",
        67: "Sự phân loại các mối liên hệ chỉ mang tính tương đối (một mối liên hệ có thể là cơ bản trong quan hệ này nhưng không cơ bản trong quan hệ khác).",
        68: "Cái riêng là phạm trù chỉ một sự vật, một hiện tượng, một quá trình riêng lẻ nhất định.",
        69: "Cái đơn nhất là phạm trù chỉ những đặc tính, tính chất chỉ vốn có ở một sự vật, hiện tượng mà không lặp lại ở sự vật khác.",
        70: "Cái chung tồn tại trong cái riêng, nhưng không bao quát hết mọi chi tiết của cái riêng. Cái riêng phong phú hơn cái chung. Nên nói 'Cái chung không gia nhập hết vào cái riêng' là đúng. Câu sai là 'Cái chung không gia nhập hết vào cái riêng' -> Wait, câu D đúng.",
        71: "Quan hệ Cái chung - Cái riêng: Cái chung tồn tại trong cái riêng. Cái riêng tồn tại trong mối liên hệ với cái chung. Câu B sai vì nói 'Cái chung không phụ thuộc vào cái riêng' (thực tế chúng không tách rời) và 'sinh ra cái riêng' (kiểu duy tâm Platon).",
        72: "Câu C sai vì 'Cái riêng tồn tại độc lập so với cái chung'. Thực tế cái riêng nào cũng chứa đựng cái chung, không thể tồn tại cô lập tuyệt đối.",
        73: "Nguyên nhân là sự tác động lẫn nhau giữa các mặt/sự vật gây ra sự biến đổi. Kết quả là sự biến đổi đó.",
        74: "Nguyên nhân (gây ra kết quả), Nguyên cớ (sự kiện ngẫu nhiên bên ngoài làm cái cớ), Điều kiện (môi trường). Chúng khác nhau nhưng liên hệ với nhau.",
        75: "Mối quan hệ nhân quả: Nguyên nhân sinh ra kết quả, nên nguyên nhân luôn có trước kết quả về mặt thời gian.",
        76: "Câu A 'Nguyên nhân có trước kết quả' là đúng. Nhân quả có tính kế thừa thời gian.",
        77: "Bản chất là tổng hợp tất cả những mặt, những mối liên hệ tất nhiên, tương đối ổn định ở bên trong sự vật, quy định sự vận động và phát triển của sự vật.",
        78: "Câu D sai. Quy luật lượng-chất: Lượng thường biến đổi chậm (tiến hóa), Chất biến đổi nhanh (nhảy vọt/cách mạng). Nhưng nói 'Chất biến đổi nhanh' không phải lúc nào cũng đúng, và 'Chất biến đổi nhanh, lượng biến đổi chậm' không phải là định nghĩa chuẩn.",
        79: "Lượng là tính quy định khách quan vốn có. Câu C sai vì nói 'Lượng phụ thuộc vào ý chí con người' (duy tâm).",
        80: "Mâu thuẫn biện chứng tồn tại khách quan và phổ biến trong cả tự nhiên, xã hội và tư duy.",
        81: "Trong mâu thuẫn biện chứng, sự thống nhất và đấu tranh của các mặt đối lập là không tách rời nhau, quy định lẫn nhau.",
        82: "Sự thống nhất là tương đối, tạm thời; sự đấu tranh là tuyệt đối (như sự vận động là tuyệt đối).",
        83: "Mâu thuẫn biện chứng là sự liên hệ, tác động qua lại vừa thống nhất vừa đấu tranh của các mặt đối lập (trong một sự vật hoặc giữa các sự vật).",
        84: "Câu A đúng: Các mặt đối lập vừa thống nhất (nương tựa nhau) vừa đấu tranh (bài trừ nhau).",
        85: "Phủ định biện chứng không xóa bỏ hoàn toàn cái cũ (câu A sai), mà chỉ loại bỏ cái tiêu cực, kế thừa cái tích cực.",
        86: "Kế thừa biện chứng là gạt bỏ những yếu tố tiêu cực, lỗi thời và giữ lại, cải biến những yếu tố tích cực, tiến bộ của cái cũ.",
        87: "Khuynh hướng phát triển theo hình 'xoáy ốc' (trôn ốc): lặp lại cái cũ nhưng ở trình độ cao hơn.",
        88: "Thực tiễn là hoạt động vật chất (câu C thiếu 'hoạt động vật chất' mà nói cả 'tinh thần' là chưa chính xác hoặc quá rộng. Nhưng câu C 'hoạt động vật chất và tinh thần' là sai vì thực tiễn là hoạt động vật chất).",
        89: "Nguyên tắc thực tiễn yêu cầu gắn lý luận với thực tiễn. Câu D 'Tách lý luận khỏi thực tiễn' là sai (bệnh giáo điều).",
        90: "Câu D đúng: Nguyên tắc thống nhất giữa lý luận và thực tiễn.",
        91: "Định nghĩa của Lênin: 'Vật chất là một phạm trù triết học dùng để chỉ thực tại khách quan...'. Đáp án B: 1-Phạm trù triết học, 2-Thực tại khách quan.",
        92: "Luận điểm này khẳng định khả năng nhận thức của con người (Khả tri luận): Cảm giác chụp lại, chép lại được thực tại khách quan.",
        93: "Định nghĩa của Lênin giải quyết cả hai mặt vấn đề cơ bản của triết học, khắc phục CNDV cũ, bác bỏ CNDT và Bất khả tri luận.",
        94: "Không gian và thời gian 'Gắn liền với nhau và với vật chất vận động'.",
        95: "Khẳng định Con người có khả năng nhận thức được thế giới khách quan (chống Bất khả tri luận).",
        96: "Diễn tả rằng ý thức là sự phản ánh (chụp lại) thế giới vật chất, và con người có thể nhận thức được.",
        97: "CNDV biện chứng coi thực tiễn/hiện thực khách quan là cơ sở, nguồn gốc, động lực và tiêu chuẩn của nhận thức.",
        98: "Phải xuất phát từ thực tế khách quan, tôn trọng quy luật khách quan (mặt vật chất quyết định), đồng thời phát huy tính năng động chủ quan (vai trò tác động của ý thức).",
        99: "Nguyên tắc 'Xuất phát từ thực tế khách quan' rút ra từ nguyên lý: Vật chất quyết định ý thức.",
        100: "Nguyên tắc 'Phát huy tính năng động chủ quan' rút ra từ: Ý thức có tính độc lập tương đối và tác động trở lại vật chất.",
        101: "Theo nguyên lý về mối liên hệ phổ biến: Các sự vật, hiện tượng có mối liên hệ, quy định, ràng buộc lẫn nhau.",
        102: "Cơ sở của mối liên hệ phổ biến là 'Tính thống nhất vật chất của thế giới'. Mọi sự vật đều là dạng cụ thể của vật chất.",
        103: "Các tính chất của mối liên hệ: Khách quan, Phổ biến, Đa dạng phong phú.",
        104: "Quan điểm toàn diện đòi hỏi xem xét đối tượng trong chỉnh thể thống nhất của tất cả các mặt, các mối liên hệ.",
        105: "Câu D 'Chỉ nhìn một chiều...' là quan điểm Phiến diện, trái ngược với quan điểm Toàn diện.",
        106: "Hai nguyên lý này có quan hệ chặt chẽ: Liên hệ để phát triển, phát triển thông qua các mối liên hệ.",
        107: "Nguồn gốc của sự phát triển nằm trong bản thân sự vật (do mâu thuẫn nội tại).",
        108: "Cái chung chỉ 'Những mặt, những thuộc tính' lặp lại.",
        109: "Cái đơn nhất là cái 'Tồn tại ở một sự vật... không lặp lại'.",
        110: "Lênin: 'Cái riêng chỉ tồn tại trong mối liên hệ đưa đến Cái chung'. (Cái riêng - Cái chung).",
        111: "Cái chung tồn tại trong Cái riêng.",
        112: "Cái riêng là bộ phận (so với toàn thế giới?) hay Cái chung là bộ phận? Lênin nói: 'Cái riêng phong phú hơn cái chung, cái chung là sâu sắc hơn cái riêng'. 'Cái chung tồn tại trong cái riêng, là một bộ phận của cái riêng'. Câu này chọn 'Cái chung/Riêng' (D) -> Cái chung là bộ phận (trong cái riêng) nhưng sâu sắc hơn.",
        113: "Lênin: 'Bất cứ Cái chung nào cũng chỉ bao quát một cách đại khái tất cả mọi vật riêng lẻ'.",
        114: "Lênin: 'Bất cứ Cái riêng nào cũng không gia nhập đầy đủ vào cái chung'.",
        115: "Muốn nhận thức cái chung, phải đi từ cái riêng (khảo sát nhiều sự vật riêng lẻ).",
        116: "Câu D sai. Phải tạo điều kiện để cái đơn nhất TÍCH CỰC trở thành cái chung, cái chung TIÊU CỰC trở thành đơn nhất (để loại bỏ). Câu D nói ngược.",
        117: "Biến cái đơn nhất (tốt) thành cái chung. Biến cái chung (xấu) thành cái đơn nhất. Chọn A (Cái chung/cái chung? No). Wait. Đáp án A: Cái chung/cái chung. Ý là: Đơn nhất -> Chung; Chung -> Đơn nhất (nhưng văn bản hỏi '...trở thành... và ... bất lợi trở thành cái đơn nhất'). Vậy chỗ trống 1 là 'cái chung', chỗ trống 2 là 'cái chung' (cái chung bất lợi). Đúng.",
        118: "Bài học về áp dụng cái chung vào cái riêng: Phải chú ý đặc điểm cụ thể của cái riêng (tình hình đất nước).",
        119: "Tìm nguyên nhân phải tìm trong những sự kiện xảy ra TRƯỚC khi hiện tượng xuất hiện (tính kế thừa thời gian).",
        120: "Muốn loại bỏ sự vật thì phải loại bỏ NGUYÊN NHÂN sinh ra nó.",
        121: "Nguyên nhân và kết quả có thể chuyển hóa cho nhau (cái là kết quả của quá trình này có thể là nguyên nhân của quá trình khác).",
        122: "Phản ánh là thuộc tính phổ biến của mọi dạng vật chất (từ vô cơ đến hữu cơ).",
        123: "Mối liên hệ là sự quy định, tác động, chuyển hóa lẫn nhau.",
        124: "Cái tất nhiên vạch đường đi cho mình xuyên qua vô số cái ngẫu nhiên.",
        125: "Sự phù hợp giữa nội dung và hình thức không cố định, mà luôn vận động, nên sự phù hợp chỉ là tạm thời (khi nội dung thay đổi, hình thức sẽ phải thay đổi theo).",
        126: "Câu D sai. Tất nhiên và Ngẫu nhiên không tồn tại độc lập, mà chúng tồn tại trong sự thống nhất biện chứng.",
        127: "Phải căn cứ vào cái tất nhiên (cái quy luật) nhưng đồng thời phải tính đến cái ngẫu nhiên (ảnh hưởng, sự cố).",
        128: "Tục ngữ này để cao Nội dung ('gỗ', 'nết') hơn hình thức ('nước sơn', 'sắc đẹp').",
        129: "Cần chú trọng cả tích lũy về Lượng để dẫn đến thay đổi về Chất (không nôn nóng hay bảo thủ).",
        130: "Cách mạng T8 là một bước nhảy toàn bộ (thay đổi toàn bộ chế độ xã hội).",
        131: "Sai lầm chủ quan nóng vội (đốt cháy giai đoạn) là vi phạm quy luật Lượng - Chất (chưa tích lũy đủ lượng đã muốn thay đổi chất).",
        132: "Bệnh 'Tả khuynh' (nôn nóng, muốn đi nhanh khi chưa đủ điều kiện).",
        133: "Câu A 'Có đi có lại mới toại lòng nhau' nói về quan hệ nhân quả hoặc quan hệ ứng xử, không rõ tính lượng-chất. Các câu B, C, D đều nói về tích lũy lượng dẫn đến kết quả (chất).",
        134: "Câu này nói về sự tích lũy số lượng (3 cây) tạo nên sức mạnh/chất mới (hòn núi cao/thành công). Quy luật Lượng - Chất.",
        135: "Tích tiểu thành đại (Tích lượng thành chất).",
        136: "Muốn thay đổi chất phải tích lũy về lượng đến điểm nút và thực hiện bước nhảy.",
        137: "Đây là mâu thuẫn cơ bản (quy định bản chất thời kỳ quá độ?). Hay mâu thuẫn chủ yếu? Thường gọi là Mâu thuẫn cơ bản.",
        138: "Mác nhấn mạnh đấu tranh là nguồn gốc của hạnh phúc/phát triển -> Quy luật mâu thuẫn (đấu tranh của các mặt đối lập).",
        139: "Nguồn gốc vận động là do Mâu thuẫn bên trong (nội tại) của sự vật.",
        140: "Đấu tranh là sự bài trừ, phủ định lẫn nhau, xu hướng đối lập.",
        141: "Bỏ qua là 'Phủ định biện chứng' (bỏ qua cái lạc hậu, kế thừa cái tiến bộ của CNTB như lực lượng sản xuất).",
        142: "Phải dựa trên quy luật khách quan, thực tiễn đất nước và xu thế thời đại. (Tất cả)",
        143: "Định nghĩa về thực tiễn phải bao gồm các yếu tố: Hoạt động vật chất, Cảm tính, Lịch sử - Xã hội, Mục đích cải tạo thế giới. Câu D đầy đủ nhất.",
        144: "Nhấn mạnh vai trò của Sản xuất vật chất (ăn, mặc, ở) là cơ sở của đời sống xã hội.",
        145: "Nhận thức là quá trình phản ánh hiện thực khách quan một cách năng động, sáng tạo.",
        146: "Câu C sai vì nói 'phản ánh nguyên xi' (đây là quan điểm của CNDV siêu hình/máy móc, không phải biện chứng).",
        147: "Cảm giác là hình thức nhận thức cảm tính đầu tiên, phản ánh thuộc tính riêng lẻ. (A)",
        148: "Lênin: 'Quan điểm về đời sống, về thực tiễn phải là quan điểm thứ nhất và cơ bản của lý luận nhận thức'.",
        149: "Chân lý là tri thức... mà con người Phản ánh và được Thực tiễn kiểm nghiệm.",
        150: "Thực tiễn... có Mục đích (nhằm cải tạo...), mang Tính lịch sử - xã hội."
    }

    count = 0
    for q in data['questions']:
        q_id = q['id']
        if q_id in explanations:
            q['explain'] = explanations[q_id]
            count += 1
            
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        
    print(f"Updated explanations for {count} questions in Chapter 2.")

if __name__ == "__main__":
    update_chapter_2()
