
import json

def update_chapter_3():
    file_path = r'c:\Users\eleven\triet-utt\exam\chuong_3.json'
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    explanations = {
        1: "Chủ nghĩa Mác đã mở đường cho việc nghiên cứu rộng rãi và toàn diện quá trình phát sinh, phát triển và suy tàn của các hình thái kinh tế - xã hội.",
        2: "Nguồn gốc sâu xa của sự vận động, phát triển xã hội là sự phát triển của lực lượng sản xuất (yếu tố động nhất).",
        3: "Sự khác biệt căn bản là con người biết Sản xuất (tạo ra tư liệu sinh hoạt), còn loài vật chỉ biết hái lượm (sử dụng cái có sẵn).",
        4: "Sản xuất vật chất là nền tảng vật chất của toàn bộ đời sống xã hội (không phải nền tảng tinh thần hay chỉ kỹ thuật).",
        5: "Lực lượng sản xuất biểu hiện mối quan hệ giữa con người với tự nhiên (khả năng chinh phục tự nhiên).",
        6: "Phương thức sản xuất là cách thức tiến hành sản xuất của cải vật chất trong một giai đoạn lịch sử nhất định (gồm LLSX và QHSX).",
        7: "Sản xuất vật chất là cơ sở tồn tại và phát triển của xã hội (nếu ngừng sản xuất vật chất, xã hội sẽ diệt vong).",
        8: "Nội dung vật chất của quá trình sản xuất bao gồm Người lao động và Tư liệu sản xuất (công cụ, đối tượng...).",
        9: "Quan hệ sản xuất là quan hệ cơ bản, đầu tiên, quyết định các quan hệ xã hội khác (quan hệ kinh tế quyết định quan hệ chính trị, đạo đức...).",
        10: "Mối quan hệ giữa LLSX và QHSX là quan hệ biện chứng giữa Nội dung (LLSX) và Hình thức (QHSX).",
        11: "Cơ sở hạ tầng là toàn bộ những quan hệ sản xuất hợp thành cơ cấu kinh tế của xã hội.",
        12: "Kiến trúc thượng tầng là toàn bộ những quan điểm, tư tưởng (chính trị, pháp quyền...) cùng các thiết chế tương ứng (nhà nước, đảng phái...) hình thành trên cơ sở hạ tầng.",
        13: "Các quan điểm, tư tưởng thuộc về Kiến trúc thượng tầng.",
        14: "Kiến trúc thượng tầng tác động trở lại cơ sở hạ tầng theo hai chiều hướng: tích cực (thúc đẩy) hoặc tiêu cực (kìm hãm) nhưng không giữ vai trò quyết định.",
        15: "Cấu trúc hình thái kinh tế - xã hội gồm: Lực lượng sản xuất, Quan hệ sản xuất (Cơ sở hạ tầng), và Kiến trúc thượng tầng.",
        16: "Nguyên nhân trực tiếp của sự ra đời giai cấp là chế độ tư hữu về tư liệu sản xuất.",
        17: "Nguyên nhân sâu xa của sự ra đời giai cấp là sự phát triển của lực lượng sản xuất (tạo ra sản phẩm thưa).",
        18: "Thực chất quan hệ giai cấp là quan hệ bóc lột và bị bóc lột (tập đoàn này chiếm đoạt lao động của tập đoàn khác).",
        19: "Cộng đồng kinh tế là đặc trưng quan trọng nhất của dân tộc (khác với bộ lạc, bộ tộc).",
        20: "Thứ tự phát triển: Thị tộc -> Bộ lạc -> Bộ tộc -> Dân tộc.",
        21: "Nguyên nhân sâu xa là sự phát triển của Lực lượng sản xuất.",
        22: "Giai cấp xuất hiện lần đầu tiên trong xã hội Chiếm hữu nô lệ (nô lệ và chủ nô).",
        23: "Đấu tranh giai cấp là động lực phát triển của các xã hội có giai cấp (dẫn đến cách mạng xã hội, thay đổi phương thức sản xuất).",
        24: "Hình thức đấu tranh đầu tiên và sơ khai nhất là Đấu tranh kinh tế (đòi tăng lương, giảm giờ làm).",
        25: "Bộ tộc hình thành khi chế độ công xã nguyên thủy tan rã và xã hội bắt đầu phân chia giai cấp (thời kỳ quá độ sang chiếm hữu nô lệ/phong kiến).",
        26: "Chức năng thống trị chính trị (giai cấp) là chức năng cơ bản, quyết định bản chất và định hướng chức năng xã hội của Nhà nước.",
        27: "Cách mạng xã hội là bước chuyển biến căn bản về chất trong toàn bộ đời sống xã hội, thay thế hình thái KT-XH cũ bằng hình thái mới cao hơn.",
        28: "Phương thức sản xuất là yếu tố quan trọng nhất, quyết định tồn tại xã hội.",
        29: "Chủ nghĩa duy tâm cho rằng Ý thức xã hội quyết định Tồn tại xã hội.",
        30: "Chủ nghĩa duy vật siêu hình thường phủ nhận tính độc lập tương đối của ý thức xã hội, coi nó hoàn toàn thụ động.",
        31: "Chủ nghĩa duy vật lịch sử khẳng định Tồn tại xã hội quyết định Ý thức xã hội, nhưng Ý thức xã hội có tính độc lập tương đối.",
        32: "Ý thức cá nhân là phương thức tồn tại và biểu hiện của ý thức xã hội ở từng con người cụ thể.",
        33: "Tồn tại xã hội là toàn bộ sinh hoạt vật chất và những điều kiện sinh hoạt vật chất của xã hội.",
        34: "Ý thức xã hội là mặt tinh thần của đời sống xã hội, bao gồm tình cảm, tập quán, tư tưởng, lý luận... nảy sinh từ tồn tại xã hội.",
        35: "Ý thức xã hội thông thường là những tri thức, quan niệm hình thành trực tiếp từ đời sống hàng ngày (chưa hệ thống hóa).",
        36: "Ý thức lý luận là những tư tưởng, quan điểm được hệ thống hóa, khái quát hóa thành các học thuyết.",
        37: "Tâm lý xã hội bao gồm tình cảm, tâm trạng, thói quen... phản ánh trực tiếp và tự phát điều kiện sống.",
        38: "Hệ tư tưởng là nhận thức lý luận, có khả năng đi sâu vào bản chất, nhưng câu C nói 'Tồn tại độc lập' là sai (nó quan hệ biện chứng với tâm lý XH).",
        39: "Trong xã hội có giai cấp, Ý thức chính trị thường giữ vai trò chủ đạo, định hướng các hình thái ý thức khác.",
        40: "Ý thức tôn giáo phản ánh hư ảo sức mạnh của tự nhiên và xã hội (thần thánh hóa).",
        41: "Ý thức khoa học phản ánh chân thực, chính xác hiện thực (Câu C nói 'phản ánh hư ảo' là sai, đó là tôn giáo).",
        42: "Con người là thực thể thống nhất giữa mặt sinh học và mặt xã hội.",
        43: "Xét đến cùng, Quan hệ sản xuất vật chất (kinh tế) chi phối các quan hệ khác.",
        44: "Theo Mác: 'Xã hội không phải là sự cộng lại của các cá nhân, mà là tổng thể những mối liên hệ...'.",
        45: "Các quy luật xã hội (lao động, giao tiếp...) giữ vai trò quyết định hình thành bản chất xã hội của con người.",
        46: "Chủ nghĩa duy vật lịch sử là sự vận dụng CNDV biện chứng vào nghiên cứu xã hội.",
        47: "Lịch sử xã hội loài người thực chất là lịch sử của sản xuất vật chất (nền tảng) và đấu tranh giai cấp (trong XH có giai cấp). Nhưng cơ bản nhất là SX vật chất.",
        48: "Sản xuất vật chất là cơ sở của sự tồn tại và phát triển của xã hội.",
        49: "C.Mác: 'Những thời đại kinh tế khác nhau không phải ở chỗ chúng sản xuất ra cái gì, mà là... bằng cách nào, với những tư liệu lao động nào'.",
        50: "Quan hệ sản xuất là quan hệ giữa người với người trong quá trình sản xuất.",
        51: "Hai mặt của phương thức sản xuất là: Lực lượng sản xuất (kỹ thuật) và Quan hệ sản xuất (xã hội).",
        52: "Người lao động là nhân tố hàng đầu, giữ vai trò quyết định trong lực lượng sản xuất.",
        53: "LLSX gồm: Người lao động và Tư liệu sản xuất.",
        54: "Quan hệ sản xuất là quan hệ cơ bản, quyết định các quan hệ khác (chính trị, pháp luật...).",
        55: "Quan hệ sở hữu về tư liệu sản xuất là quan hệ xuất phát, cơ bản nhất, quyết định các quan hệ khác (tổ chức, phân phối).",
        56: "LLSX và QHSX thống nhất và đấu tranh (biện chứng).",
        57: "Phương án A sai. Quan hệ sản xuất CÓ tác động trở lại lực lượng sản xuất.",
        58: "Quy luật Quan hệ sản xuất phù hợp với trình độ phát triển của Lực lượng sản xuất là quy luật cơ bản, phổ biến nhất.",
        59: "Mâu thuẫn giữa LLSX và QHSX là động lực cơ bản nhất.",
        60: "Quan hệ sản xuất là Hình thức xã hội của quá trình sản xuất (LLSX là nội dung).",
        61: "Câu C sai nếu hiểu 'quyết định tính chất' theo nghĩa tuyệt đối mà không thấy vai trò của LLSX. Thực tế LLSX quyết định QHSX. Phương án C nói 'QHSX quyết định... LLSX' là sai quy luật.",
        62: "Kiến trúc thượng tầng tiêu biểu cho bộ mặt tinh thần của xã hội.",
        63: "Công cụ lao động là yếu tố động nhất, cách mạng nhất, thể hiện rõ nhất trình độ phát triển của LLSX.",
        64: "Kiến trúc thượng tầng có tính độc lập tương đối so với cơ sở hạ tầng.",
        65: "Cơ sở hạ tầng quyết định kiến trúc thượng tầng.",
        66: "Nhà nước (Tổ chức chính trị) là yếu tố mạnh nhất trong KTTT.",
        67: "Quan hệ biện chứng: CSHT quyết định KTTT.",
        68: "Lịch sử trải qua 5 hình thái: CSNT -> Chiếm hữu nô lệ -> Phong kiến -> TBCN -> CSCN.",
        69: "Nguyên nhân của đấu tranh giai cấp là sự đối lập về lợi ích cơ bản (kinh tế).",
        70: "Nguyên nhân trực tiếp ra đời nhà nước là mâu thuẫn giai cấp gay gắt không thể điều hòa được.",
        71: "Nguyên nhân sâu xa là sự phát triển của LLSX dẫn đến chế độ tư hữu.",
        72: "Bản chất nhà nước là công cụ chuyên chính của giai cấp thống trị.",
        73: "Nguồn gốc trực tiếp của CM xã hội là Đấu tranh giai cấp.",
        74: "Nguồn gốc sâu xa của CM xã hội là mâu thuẫn giữa LLSX và QHSX.",
        75: "Thời cơ cách mạng là thời điểm chín muồi của điều kiện khách quan và nhân tố chủ quan.",
        76: "Đối tượng của cách mạng là giai cấp thống trị lỗi thời cần đánh đổ.",
        77: "Ý thức xã hội lạc hậu do: Sức mạnh thói quen, tập quán; Ý thức xh phản ánh tồn tại xh nên biến đổi sau; Lợi ích của giai cấp thống trị muốn duy trì cái cũ.",
        78: "Tồn tại xã hội quyết định ý thức xã hội.",
        79: "Chủ nghĩa duy vật lịch sử.",
        80: "Hoạt động thực tiễn của con người (cách mạng, giáo dục...) là điều kiện để ý thức tác động trở lại.",
        81: "Quan điểm C sai: 'Ý thức xã hội quyết định tồn tại xã hội' (đây là duy tâm).",
        82: "Biểu hiện lạc hậu: Xã hội cũ mất đi nhưng ý thức cũ vẫn còn tồn tại dai dẳng.",
        83: "Câu C sai: 'Ý thức xã hội hoàn toàn thụ động' (nó có tính độc lập).",
        84: "Bản chất xã hội thể hiện khi con người tồn tại trong các quan hệ xã hội.",
        85: "Con người là một bộ phận của giới tự nhiên (nhưng có mặt xã hội).",
        86: "Con người là chủ thể lịch sử: Con người tạo ra lịch sử thông qua hoạt động thực tiễn tuân theo quy luật.",
        87: "Con người là sản phẩm của lịch sử: Con người chịu sự quy định của điều kiện lịch sử.",
        88: "Quần chúng nhân dân là người sáng tạo chân chính ra lịch sử (sản xuất vật chất, cách mạng, văn hóa).",
        89: "Câu D sai.",
        90: "Đời sống tinh thần hình thành trên cơ sở đời sống vật chất.",
        91: "Phải tìm cơ sở trong nền sản xuất vật chất.",
        92: "Loài vật: Hái lượm; Con người: Sản xuất.",
        93: "Cối xay tay -> Phong kiến; Cối xay hơi nước -> TBCN: Lực lượng sản xuất (công cụ) quyết định Quan hệ sản xuất (chế độ xã hội).",
        94: "Khi QHSX lỗi thời, lạc hậu (hoặc vượt trước quá xa) so với trình độ LLSX, nó trở thành xiềng xích.",
        95: "Phải thay đổi QHSX thông qua cách mạng xã hội.",
        96: "Phản ánh xu hướng tất yếu khách quan của lịch sử.",
        97: "Với những 'Tư liệu lao động' (cụ thể là công cụ). Câu nói nổi tiếng của Mác.",
        98: "QHSX tác động trở lại: thúc đẩy (nếu phù hợp) hoặc kìm hãm (nếu không phù hợp).",
        99: "Lịch sử xã hội là lịch sử thay thế của các phương thức sản xuất.",
        100: "Phải bắt đầu từ phát triển Lực lượng sản xuất (Lực lượng lao động và Công cụ lao động).",
        101: "Căn cứ vào Trình độ phát triển của Lực lượng sản xuất.",
        102: "Do sự phát triển của Lực lượng sản xuất (yếu tố gốc rễ).",
        103: "Phát triển kinh tế thị trường định hướng XHCN (để phát triển LLSX).",
        104: "Sự nhất trí về chính trị và tinh thần (dựa trên công hữu và lợi ích chung).",
        105: "Kinh tế (CSHT) và Chính trị-xã hội (KTTT).",
        106: "Kiến trúc thượng tầng thường xuyên tác động trở lại cơ sở hạ tầng.",
        107: "Quy luật CSHT và KTTT (Kinh tế và Chính trị).",
        108: "Hệ tư tưởng của giai cấp công nhân (tiên tiến, khoa học).",
        109: "Quan điểm 'Duy vật tầm thường' (chỉ thấy kinh tế, coi nhẹ chính trị/ý thức).",
        110: "Đổi mới Kinh tế làm trung tâm (nhận thức lại về CNXH).",
        111: "Bỏ qua chế độ Tư bản chủ nghĩa.",
        112: "Bỏ qua việc xác lập vị trí thống trị của QHSX và KTTT tư bản chủ nghĩa, nhưng kế thừa thành tựu.",
        113: "Quy luật khách quan (nhất là quy luật về sự phù hợp của QHSX với LLSX).",
        114: "Dùng cho xã hội trong từng giai đoạn lịch sử nhất định (cấu trúc cụ thể).",
        115: "Bắt đầu từ phát triển Lực lượng sản xuất.",
        116: "Học thuyết Hình thái kinh tế - xã hội.",
        117: "Phát triển Lực lượng lao động và Công cụ lao động (các yếu tố của LLSX).",
        118: "Quy luật QHSX phù hợp với trình độ LLSX.",
        119: "Quy luật QHSX phù hợp với trình độ LLSX (phát triển nhiều thành phần kinh tế để phù hợp với trình độ LLSX còn thấp/không đều).",
        120: "Quy luật QHSX phù hợp với trình độ LLSX (vấn đề then chốt).",
        121: "Thể hiện sự KHÔNG phù hợp (A nói 'sự phù hợp' là sai).",
        122: "Chế độ Công hữu về tư liệu sản xuất.",
        123: "Lực lượng sản xuất ... mâu thuẫn với ... Quan hệ sản xuất.",
        124: "Kinh tế nhiều thành phần, Kinh tế nhà nước giữ vai trò chủ đạo/nền tảng.",
        125: "Tránh chủ quan duy ý chí (nóng vội xóa bỏ các thành phần kinh tế, áp đặt QHSX khi chưa đủ điều kiện).",
        126: "Phương án B (sai): Xuất phát từ chủ quan duy ý chí là sai lầm cần tránh.",
        127: "Từng bước xóa bỏ tàn dư... (không thể xóa ngay lập tức).",
        128: "Ý thức tôn giáo.",
        129: "Tính kế thừa của ý thức xã hội.",
        130: "Tính vượt trước (Tri thức khoa học dự báo và mở đường). Hoặc có thể hiểu là vai trò của khoa học. Nhưng trong văn cảnh 'minh chứng cho điều gì' về tính chất của YTXH thì thường là tính vượt trước/tiên phong.",
        131: "Sức mạnh của tập quán (Tính lạc hậu/bảo thủ nhưng có sức mạnh to lớn).",
        132: "Phương án D (sai): Không thể 'Xóa bỏ tất cả' (cần kế thừa cái tốt).",
        133: "Ý thức Triết học? Hay Nghệ thuật? Mác nói về nghệ thuật/văn hóa. Nhưng câu hỏi này hơi đặc thù. Thường thì Triết học là hạt nhân lý luận. Tuy nhiên 'linh hồn sống' thường ám chỉ cái gì đó gần gũi cảm xúc. Nhưng đáp án A là Triết học.",
        134: "Ý thức Nghệ thuật (hình vẽ hang động...) hoặc Tôn giáo sơ khai. Nhưng Nghệ thuật thường được coi là rất sớm. Đáp án A.",
        135: "Ý thức Khoa học (phản ánh chân thực, khách quan).",
        136: "Coi trọng vai trò kinh tế, nhưng cũng tôn trọng tính độc lập và phát huy vai trò của ý thức xã hội (D).",
        137: "Phương án C (sai): Xóa bỏ tất cả giá trị truyền thống là sai lầm (phủ định sạch trơn).",
        138: "Tính lạc hậu của ý thức xã hội (tư tưởng phong kiến còn sót lại).",
        139: "Tính lạc hậu.",
        140: "Kế thừa và phát huy giá trị tốt đẹp (A).",
        141: "Xóa bỏ dần những phong tục lạc hậu (A).",
        142: "Phương án B (sai): Đề cao chủ nghĩa cá nhân là không đúng với quan điểm của Đảng (đề cao lợi ích tập thể/hài hòa).",
        143: "Kết hợp hài hòa vai trò lãnh tụ và quần chúng (D).",
        144: "Sùng bái cá nhân (A).",
        145: "Xem nhẹ vai trò cá nhân/lãnh tụ (B).",
        146: "Nhấn mạnh bản chất xã hội của con người (B).",
        147: "Tàn dư xã hội cũ cần xóa bỏ (A).",
        148: "Giải quyết hài hòa lợi ích cá nhân và xã hội (C).",
        149: "Kết hợp lợi ích vật chất và tinh thần (A).",
        150: "Môi trường xã hội ảnh hưởng đến nhân cách (B)."
    }

    count = 0
    for q in data['questions']:
        q_id = q['id']
        if q_id in explanations:
            q['explain'] = explanations[q_id]
            count += 1
            
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        
    print(f"Updated explanations for {count} questions in Chapter 3.")

if __name__ == "__main__":
    update_chapter_3()
