const fs = require('fs');

const path = 'c:/Users/eleven/triet-utt/subjects/ptit/phap-luat-dai-cuong/exam/2.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));

const explanations = {
    1: "Hiến pháp là đạo luật cơ bản của nhà nước, có hiệu lực pháp lý cao nhất, quy định chế độ chính trị, kinh tế, văn hóa, xã hội...",
    2: "Pháp luật có 3 thuộc tính cơ bản: Tính quy phạm phổ biến, Tính xác định chặt chẽ về mặt hình thức, và Tính được đảm bảo bằng nhà nước.",
    3: "Nhà nước và pháp luật đều thuộc kiến trúc thượng tầng của xã hội, được quyết định bởi cơ sở hạ tầng.",
    4: "Nhà nước và pháp luật đều thuộc kiến trúc thượng tầng của xã hội.",
    5: "Các tổ chức xã hội chỉ được ban hành văn bản mang tính pháp lý khi được Nhà nước trao quyền.",
    6: "Quy phạm pháp luật có tính bắt buộc chung, áp dụng cho mọi chủ thể và được nhà nước bảo đảm thực hiện.",
    7: "Cấu trúc của quy phạm pháp luật gồm Giả định, Quy định, Chế tài, nhưng không nhất thiết phải có đủ 3 bộ phận trong một điều luật.",
    8: "Quy phạm pháp luật được áp dụng nhiều lần trong thực tế đời sống nhưng chỉ trong những hoàn cảnh, điều kiện nhất định.",
    9: "Áp dụng tương tự pháp luật xảy ra khi thiếu quy phạm trực tiếp điều chỉnh nhưng có quy phạm tương tự.",
    10: "Ủy ban Thường vụ Quốc hội có thẩm quyền ban hành Pháp lệnh và Nghị quyết.",
    11: "Theo Luật Ban hành văn bản QPPL 2015, Ủy ban nhân dân các cấp chỉ ban hành Quyết định.",
    12: "Quốc hội là cơ quan duy nhất có quyền lập hiến và lập pháp (ban hành Hiến pháp và Luật).",
    13: "Văn bản QPPL hết hiệu lực khi hết thời hạn, bị bãi bỏ/hủy bỏ, hoặc được thay thế bằng văn bản mới.",
    14: "Hội đồng nhân dân ban hành Nghị quyết để quyết định các vấn đề quan trọng của địa phương.",
    15: "Trong hệ thống văn bản quy phạm pháp luật, Nghị định của Chính phủ có hiệu lực pháp lý cao hơn Thông tư và Quyết định (của UBND).",
    16: "Quy phạm pháp luật khác quy phạm xã hội ở chỗ nó mang tính bắt buộc chung và được Nhà nước bảo đảm thực hiện.",
    17: "Chế tài là bộ phận quy định các biện pháp tác động (thường là bất lợi) áp dụng đối với chủ thể vi phạm.",
    18: "Nguồn của pháp luật Việt Nam hiện nay bao gồm Văn bản quy phạm pháp luật, Tập quán pháp và Án lệ (tiền lệ pháp).",
    19: "Theo Luật Ban hành VBQPPL 2015, Quyết định của Tổng Kiểm toán Nhà nước là văn bản quy phạm pháp luật.",
    20: "Bộ trưởng, Thủ trưởng cơ quan ngang bộ có thẩm quyền ban hành Thông tư.",
    21: "Chỉ có Tòa án nhân dân mới có quyền tuyên bố hạn chế năng lực hành vi dân sự của cá nhân.",
    22: "Các yếu tố cấu thành quan hệ pháp luật bao gồm Chủ thể, Khách thể và Nội dung (kèm theo sự kiện pháp lý làm căn cứ phát sinh).",
    23: "Năng lực pháp luật dân sự của cá nhân là khả năng có quyền và nghĩa vụ, do Nhà nước quy định và mọi cá nhân đều bình đẳng.",
    24: "Mọi chủ thể tham gia quan hệ pháp luật đều phải có năng lực pháp luật.",
    25: "Sự kiện pháp lý cùng với quy phạm pháp luật và năng lực chủ thể là điều kiện phát sinh, thay đổi, chấm dứt quan hệ pháp luật.",
    26: "Quan hệ pháp luật hình thành dựa trên cơ sở các quy định của pháp luật (ý chí của Nhà nước) và sự tham gia của các chủ thể.",
    27: "Năng lực pháp luật của cá nhân có từ khi sinh ra và chấm dứt khi chết.",
    28: "Năng lực hành vi dân sự của cá nhân phụ thuộc vào độ tuổi và khả năng nhận thức, làm chủ hành vi.",
    29: "Năng lực chủ thể của pháp nhân phát sinh từ thời điểm được cơ quan nhà nước có thẩm quyền thành lập hoặc cho phép thành lập.",
    30: "Sự biến pháp lý là những sự kiện xảy ra không phụ thuộc vào ý chí con người nhưng làm phát sinh hậu quả pháp lý.",
    31: "Người từ đủ 6 tuổi đến chưa đủ 18 tuổi có năng lực hành vi dân sự chưa đầy đủ (khi tham gia giao dịch cần người đại diện).",
    32: "Người chưa đủ 6 tuổi không có năng lực hành vi dân sự.",
    33: "Năng lực hành vi là khả năng của cá nhân bằng hành vi của mình xác lập, thực hiện quyền và nghĩa vụ dân sự.",
    34: "Quan hệ pháp luật gồm 3 yếu tố cấu thành: Chủ thể, Khách thể và Nội dung.",
    35: "Cấu thành của quan hệ pháp luật gồm Chủ thể, Khách thể và Nội dung.",
    36: "Trách nhiệm hình sự là loại trách nhiệm pháp lý nghiêm khắc nhất, do Tòa án áp dụng đối với người phạm tội.",
    37: "Cấu thành vi phạm pháp luật gồm 4 yếu tố: Mặt khách quan, Mặt chủ quan, Chủ thể và Khách thể.",
    38: "Mối quan hệ nhân quả giữa hành vi và hậu quả là khách quan, không phụ thuộc vào việc hậu quả có phù hợp với mục đích của chủ thể hay không.",
    39: "Nội dung của trách nhiệm pháp lý là nghĩa vụ gánh chịu hậu quả bất lợi của chủ thể vi phạm.",
    40: "Năng lực pháp luật của pháp nhân chấm dứt khi pháp nhân chấm dứt tồn tại (giải thể, phá sản, hợp nhất...).",
    41: "Viện kiểm sát nhân dân thực hành quyền công tố và kiểm sát hoạt động tư pháp.",
    42: "Đất đai thuộc sở hữu toàn dân, cá nhân/tổ chức chỉ có quyền sử dụng, không có quyền sở hữu.",
    43: "Luật Đầu tư là văn bản luật thuộc ngành Luật Kinh tế, không phải là một ngành luật độc lập trong hệ thống phân loại truyền thống.",
    44: "Luật Cạnh tranh là một chế định thuộc ngành Luật Kinh tế, không phải là một ngành luật độc lập.",
    45: "Các chính sách vĩ mô về văn hóa, giáo dục thường được quy định trong Hiến pháp và Luật Tổ chức bộ máy nhà nước.",
    46: "Giao dịch dân sự là đối tượng điều chỉnh chủ yếu của ngành Luật Dân sự.",
    47: "Nghị quyết của Quốc hội là văn bản có tính chất đạo luật, dùng để quyết định các vấn đề quan trọng.",
    48: "Công dân đủ 21 tuổi trở lên có quyền ứng cử vào Quốc hội, Hội đồng nhân dân.",
    49: "Cơ cấu Chính phủ (nhiệm kỳ 2016-2021 và 2021-2026) có 18 Bộ.",
    50: "Cơ cấu Chính phủ hiện nay có 4 cơ quan ngang Bộ.",
    51: "Thanh tra Chính phủ là cơ quan ngang Bộ.",
    52: "Văn phòng Chính phủ là cơ quan ngang Bộ.",
    53: "Văn phòng Chính phủ là cơ quan ngang Bộ.",
    54: "Chính phủ là cơ quan hành chính nhà nước cao nhất của nước CHXHCN Việt Nam.",
    55: "Cảnh cáo và Phạt tiền là hai hình thức xử phạt chính được quy định trong Luật Xử lý vi phạm hành chính.",
    56: "Tước quyền sử dụng giấy phép, tịch thu tang vật phương tiện là các hình thức xử phạt bổ sung.",
    57: "Trong xử phạt hành chính, hình phạt chính có thể áp dụng độc lập, hình phạt bổ sung không áp dụng độc lập.",
    58: "Các biện pháp cưỡng chế hành chính bao gồm: xử phạt hành chính, các biện pháp ngăn chặn và các biện pháp phòng ngừa.",
    59: "Trách nhiệm hành chính bao gồm việc áp dụng các hình thức xử phạt và các biện pháp khắc phục hậu quả.",
    60: "Người từ đủ 14 tuổi trở lên có thể bị xử phạt vi phạm hành chính (tùy theo mức độ lỗi và loại vi phạm).",
    61: "Tước quyền sử dụng giấy phép và tịch thu tang vật là hình thức xử phạt bổ sung (hoặc chính tùy trường hợp, nhưng thường dùng bổ sung).",
    62: "Quan hệ pháp luật hành chính mang tính quyền lực - phục tùng, một bên chủ thể luôn mang quyền lực nhà nước.",
    63: "Trong vi phạm hành chính, chủ thể vi phạm phải chịu trách nhiệm trước Nhà nước.",
    64: "Quan hệ hành chính có thể phát sinh do ý chí/yêu cầu của một bên mà không cần sự thỏa thuận của bên kia.",
    65: "Quan hệ pháp luật hành chính gắn liền với hoạt động chấp hành và điều hành của cơ quan nhà nước.",
    66: "Tòa hình sự có thẩm quyền xét xử các vụ án hình sự và tuyên bản án hình sự.",
    67: "Bộ luật Hình sự hiện hành là Bộ luật Hình sự năm 2015 (sửa đổi, bổ sung 2017).",
    68: "Hoạt động khởi tố, hỏi cung bị can thuộc phạm vi điều chỉnh của ngành Luật Tố tụng hình sự.",
    69: "Hoạt động điều tra vụ án hình sự do ngành Luật Tố tụng hình sự điều chỉnh.",
    70: "Các nguyên tắc cơ bản của Luật Hình sự bao gồm nguyên tắc Pháp chế, Dân chủ, Nhân đạo...",
    71: "Các nguyên tắc cơ bản của Luật Hình sự bao gồm nguyên tắc Pháp chế, Dân chủ, Nhân đạo...",
    72: "Các nguyên tắc cơ bản của Luật Hình sự bao gồm nguyên tắc Pháp chế, Dân chủ, Nhân đạo...",
    73: "Đối với mỗi tội phạm, người phạm tội chỉ bị áp dụng một hình phạt chính và có thể áp dụng thêm một hoặc nhiều hình phạt bổ sung.",
    74: "Bộ luật Hình sự 2015 quy định hệ thống hình phạt gồm 7 hình phạt chính và 7 hình phạt bổ sung.",
    75: "Phạt tiền có thể là hình phạt chính hoặc hình phạt bổ sung tùy theo quy định đối với từng tội danh.",
    76: "Tịch thu tài sản chỉ được áp dụng là hình phạt bổ sung đối với tội phạm nghiêm trọng trở lên.",
    77: "Cấm đảm nhiệm chức vụ, cấm hành nghề là hình phạt bổ sung.",
    78: "Cải tạo không giam giữ là một loại hình phạt chính, áp dụng đối với tội phạm ít nghiêm trọng.",
    79: "Bộ luật Hình sự 2015 quy định chủ thể của tội phạm bao gồm cá nhân và pháp nhân thương mại (đối với một số tội danh).",
    80: "Bộ luật Hình sự 2015 quy định chủ thể của tội phạm bao gồm cá nhân và pháp nhân thương mại.",
    81: "Cấu thành tội phạm gồm 4 yếu tố: Mặt khách quan, Mặt chủ quan, Chủ thể và Khách thể.",
    82: "Trong vụ án hình sự thường có phần trách nhiệm dân sự (bồi thường thiệt hại do tội phạm gây ra).",
    83: "Khi tổng hợp hình phạt của nhiều bản án, mức cao nhất của tù có thời hạn là 30 năm.",
    84: "Mức tối đa của hình phạt tù có thời hạn đối với một tội là 20 năm.",
    85: "Hình phạt chỉ được thi hành khi bản án hoặc quyết định của Tòa án đã có hiệu lực pháp luật.",
    86: "Trình tự tố tụng hình sự: Khởi tố -> Điều tra -> Truy tố -> Xét xử.",
    87: "Bộ Tư pháp là cơ quan hành chính nhà nước (thuộc Chính phủ).",
    88: "Cấm đảm nhiệm chức vụ được áp dụng khi xét thấy việc người bị kết án giữ chức vụ gây nguy hại cho xã hội.",
    89: "Cải tạo không giam giữ là hình phạt chính.",
    90: "Tù chung thân là hình phạt chính, áp dụng không thời hạn đối với người phạm tội đặc biệt nghiêm trọng.",
    91: "Tước một số quyền công dân là hình phạt bổ sung.",
    92: "Trục xuất không áp dụng đối với công dân Việt Nam (chỉ áp dụng với người nước ngoài).",
    93: "Tử hình là hình phạt tước bỏ quyền sống của người phạm tội.",
    94: "Các hình phạt trong BLHS gồm Cảnh cáo, Phạt tiền, Cải tạo không giam giữ, Trục xuất, Tù có thời hạn...",
    95: "Các biện pháp như Bắt tạm giam là biện pháp ngăn chặn, không phải là hình phạt.",
    96: "Tòa hình sự có thẩm quyền xét xử sơ thẩm các vụ án hình sự.",
    97: "Người chưa thành niên là người chưa đủ 18 tuổi.",
    98: "Người nhận cầm cố có quyền chiếm hữu (nắm giữ) tài sản cầm cố trong thời hạn hợp đồng.",
    99: "Hàng thừa kế thứ nhất gồm: vợ, chồng, cha đẻ, mẹ đẻ, cha nuôi, mẹ nuôi, con đẻ, con nuôi.",
    100: "Người thừa kế phải là người còn sống vào thời điểm mở thừa kế hoặc sinh ra và còn sống sau thời điểm mở thừa kế nhưng đã thành thai trước khi người để lại di sản chết.",
    101: "Thừa kế theo pháp luật được áp dụng khi không có di chúc, di chúc không hợp pháp hoặc người thừa kế theo di chúc chết trước người để lại di sản...",
    102: "Con chưa thành niên là đối tượng được hưởng thừa kế không phụ thuộc vào nội dung di chúc (kỷ phần bắt buộc).",
    103: "Vợ hoặc chồng là đối tượng được hưởng thừa kế không phụ thuộc vào nội dung di chúc.",
    104: "Cha, mẹ là đối tượng được hưởng thừa kế không phụ thuộc vào nội dung di chúc.",
    105: "Con đã thành niên mà không có khả năng lao động được hưởng thừa kế không phụ thuộc vào nội dung di chúc.",
    106: "Di chúc miệng mặc nhiên bị hủy bỏ sau 3 tháng nếu người lập di chúc còn sống, minh mẫn, sáng suốt.",
    107: "Hàng thừa kế thứ nhất gồm: vợ, chồng, cha đẻ, mẹ đẻ, cha nuôi, mẹ nuôi, con đẻ, con nuôi.",
    108: "Cá nhân có năng lực hành vi dân sự đầy đủ khi đủ 18 tuổi trở lên (trừ trường hợp bị mất/hạn chế năng lực hành vi).",
    109: "Trong nhà nước chủ nô, giai cấp thống trị là giai cấp Chủ nô.",
    110: "Trong nhà nước phong kiến, giai cấp thống trị là giai cấp Địa chủ phong kiến.",
    111: "Trong nhà nước tư sản, giai cấp thống trị là giai cấp Tư sản.",
    112: "Trong nhà nước XHCN, giai cấp lãnh đạo là giai cấp Công nhân (cùng nhân dân lao động làm chủ).",
    113: "Giai cấp bị trị trong nhà nước chủ nô là giai cấp Nô lệ.",
    114: "Giai cấp bị trị trong nhà nước phong kiến là giai cấp Nông dân.",
    115: "Giai cấp bị trị trong nhà nước tư sản là giai cấp Công nhân (Vô sản).",
    116: "Pháp luật chủ nô phản ánh ý chí của giai cấp Chủ nô.",
    117: "Pháp luật phong kiến phản ánh ý chí của giai cấp thống trị (Địa chủ phong kiến).",
    118: "Pháp luật tư sản phản ánh ý chí của giai cấp Tư sản.",
    119: "Nhà nước ra đời và tồn tại khi xã hội có sự phân chia giai cấp và đấu tranh giai cấp.",
    120: "Pháp luật ra đời và tồn tại trong xã hội có giai cấp và nhà nước.",
    121: "Nhà nước sẽ tiêu vong khi xã hội không còn giai cấp và đấu tranh giai cấp (xã hội cộng sản chủ nghĩa).",
    122: "Pháp luật sẽ tiêu vong khi những điều kiện xã hội cho sự tồn tại của nó (giai cấp, nhà nước) không còn."
};

let updatedCount = 0;
data.questions.forEach(q => {
    if (explanations[q.id]) {
        q.explain = explanations[q.id];
        updatedCount++;
    }
});

console.log(`Updated ${updatedCount} questions.`);
fs.writeFileSync(path, JSON.stringify(data, null, 4), 'utf8');
console.log('File saved.');
